- name: 'Sync api'
  become: true
  synchronize:
    src: '../../dist/demo-devops/'
    dest: /var/www/
    archive: false
    checksum: true
    recursive: true
    delete: true

- name: Creating a .npmrc
  become: true
  copy:
    dest: '/var/www/.npmrc'
    content: |
      auto-install-peers=true
      strict-peer-dependencies=false

- name: Install deps for api
  environment:
    PATH: '/usr/local/lib/npm/bin:{{ ansible_env.PATH }}'
  shell:
    cmd: pnpm install --prod
    chdir: /var/www/

- name: Add ecosystem.config.js
  become: true
  template:
    src: './templates/ecosystem.config.js'
    dest: /var/www/ecosystem.config.js

- name: Start API
  become: true
  shell:
    cmd: pm2 start ecosystem.config.js
    chdir: /var/www/
