ungrouped:
  hosts:
    main_server:
      ansible_connection: ssh
      ansible_host: "{{ lookup('env','ANSIBLE_HOST')}}"
      ansible_user: "{{ lookup('env','ANSIBLE_USER')}}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'PRIVATE_KEY') | default('~/.ssh/demo', true) }}"
